-- Generated by scripts/cleanup-fabricated-stocks.ts
-- Mode: DRY-RUN | Generated: 2026-04-25T19:23:06.361Z
-- Each bucket is wrapped in a transaction. Review and run individually.
-- Buckets: A = remap (rewrite linkages, drop orphan); B = delete (cascade);
--          C = rename (UPDATE name only)

-- ============================================================
-- BUCKET A — REMAP (38 rows)
-- For each, rewrite post_stocks linkages from source → target,
-- drop any duplicate-pair rows, then delete the source stock.
-- ============================================================
BEGIN;
-- CELSIUS (US, name="Celsius Network", 1 linkages) → CELH
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'CELH' LIMIT 1) WHERE stock_id = 'ab1a4149-3742-40fd-ae06-4014ffde9522' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'CELH' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'ab1a4149-3742-40fd-ae06-4014ffde9522';
DELETE FROM stocks WHERE id = 'ab1a4149-3742-40fd-ae06-4014ffde9522';
-- FORTUNE (US, name="Fortinet, Inc.", 1 linkages) → FTNT
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'FTNT' LIMIT 1) WHERE stock_id = '310ff941-878a-49ea-81ba-eef409dff773' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'FTNT' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '310ff941-878a-49ea-81ba-eef409dff773';
DELETE FROM stocks WHERE id = '310ff941-878a-49ea-81ba-eef409dff773';
-- CORNING (US, name="Corning Incorporated", 1 linkages) → GLW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'GLW' LIMIT 1) WHERE stock_id = '0ba77566-27b5-4f1f-8438-ab32e43f7490' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'GLW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '0ba77566-27b5-4f1f-8438-ab32e43f7490';
DELETE FROM stocks WHERE id = '0ba77566-27b5-4f1f-8438-ab32e43f7490';
-- AP MEMORY (TW, name="AP Memory Inc.", 0 linkages) → 6531.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1) WHERE stock_id = '56f01c73-02ec-4cb2-a0a0-4adc9e69aade' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '56f01c73-02ec-4cb2-a0a0-4adc9e69aade';
DELETE FROM stocks WHERE id = '56f01c73-02ec-4cb2-a0a0-4adc9e69aade';
-- BROADCOM (US, name="Broadcom Inc.", 1 linkages) → AVGO
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'AVGO' LIMIT 1) WHERE stock_id = '6e12bee8-d22d-4b62-992e-65d4736a10a5' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'AVGO' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '6e12bee8-d22d-4b62-992e-65d4736a10a5';
DELETE FROM stocks WHERE id = '6e12bee8-d22d-4b62-992e-65d4736a10a5';
-- CONFLUENT (US, name="Confluent, Inc.", 4 linkages) → CFLT
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'CFLT' LIMIT 1) WHERE stock_id = '0d0cf1e9-fe63-4ee6-b70f-c006bd453796' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'CFLT' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '0d0cf1e9-fe63-4ee6-b70f-c006bd453796';
DELETE FROM stocks WHERE id = '0d0cf1e9-fe63-4ee6-b70f-c006bd453796';
-- 6531 (TW, name="APMemory Inc.", 0 linkages) → 6531.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1) WHERE stock_id = 'b3875e13-0ce6-4288-9f32-da04573e123e' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'b3875e13-0ce6-4288-9f32-da04573e123e';
DELETE FROM stocks WHERE id = 'b3875e13-0ce6-4288-9f32-da04573e123e';
-- PNTIR (US, name="Palantir Technologies Inc.", 0 linkages) → PLTR
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1) WHERE stock_id = '5d9af923-1993-4f34-9b98-cda2f4b89cfb' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '5d9af923-1993-4f34-9b98-cda2f4b89cfb';
DELETE FROM stocks WHERE id = '5d9af923-1993-4f34-9b98-cda2f4b89cfb';
-- MARVELL (US, name="Marvell Technology, Inc.", 6 linkages) → MRVL
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'MRVL' LIMIT 1) WHERE stock_id = '1ae6d645-884e-4604-a16f-9f8f08f1cbff' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'MRVL' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '1ae6d645-884e-4604-a16f-9f8f08f1cbff';
DELETE FROM stocks WHERE id = '1ae6d645-884e-4604-a16f-9f8f08f1cbff';
-- 2408 (TW, name="南亞科", 0 linkages) → 2408.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '2408.TW' LIMIT 1) WHERE stock_id = '6c54795c-e67b-4dcc-a56a-a623654065e7' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '2408.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '6c54795c-e67b-4dcc-a56a-a623654065e7';
DELETE FROM stocks WHERE id = '6c54795c-e67b-4dcc-a56a-a623654065e7';
-- CLOUDFLARE (US, name="Cloudflare, Inc.", 3 linkages) → NET
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1) WHERE stock_id = '7d091c4b-4982-4b1f-a082-df1490d4fd85' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '7d091c4b-4982-4b1f-a082-df1490d4fd85';
DELETE FROM stocks WHERE id = '7d091c4b-4982-4b1f-a082-df1490d4fd85';
-- SFDC (US, name="Salesforce, Inc.", 0 linkages) → CRM
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'CRM' LIMIT 1) WHERE stock_id = '1b6bb728-adc0-4178-a8bb-6111da83033e' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'CRM' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '1b6bb728-adc0-4178-a8bb-6111da83033e';
DELETE FROM stocks WHERE id = '1b6bb728-adc0-4178-a8bb-6111da83033e';
-- CLOUDFRE (US, name="Cloudflare, Inc.", 0 linkages) → NET
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1) WHERE stock_id = 'e1111437-bf57-45a5-b65f-d67e8270c16d' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'e1111437-bf57-45a5-b65f-d67e8270c16d';
DELETE FROM stocks WHERE id = 'e1111437-bf57-45a5-b65f-d67e8270c16d';
-- PALANTIR (US, name="Palantir Technologies Inc.", 2 linkages) → PLTR
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1) WHERE stock_id = '40857028-0cd8-4f9c-a431-0cc11dd7a118' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '40857028-0cd8-4f9c-a431-0cc11dd7a118';
DELETE FROM stocks WHERE id = '40857028-0cd8-4f9c-a431-0cc11dd7a118';
-- APMEMORY (TW, name="APMemory Inc.", 1 linkages) → 6531.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1) WHERE stock_id = 'b904409b-7c07-46ff-96cb-b621c6c7ed1b' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '6531.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'b904409b-7c07-46ff-96cb-b621c6c7ed1b';
DELETE FROM stocks WHERE id = 'b904409b-7c07-46ff-96cb-b621c6c7ed1b';
-- PANTR (US, name="Palantir Technologies Inc.", 0 linkages) → PLTR
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1) WHERE stock_id = 'de1993d9-fd62-4d4d-b48e-0e87389128d1' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PLTR' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'de1993d9-fd62-4d4d-b48e-0e87389128d1';
DELETE FROM stocks WHERE id = 'de1993d9-fd62-4d4d-b48e-0e87389128d1';
-- 4966 (TW, name="普瑞", 1 linkages) → 4966.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '4966.TW' LIMIT 1) WHERE stock_id = '3fd4bcd8-93ef-4a7a-b240-f93c19cf83c9' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '4966.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '3fd4bcd8-93ef-4a7a-b240-f93c19cf83c9';
DELETE FROM stocks WHERE id = '3fd4bcd8-93ef-4a7a-b240-f93c19cf83c9';
-- 8299 (TW, name="8299", 1 linkages) → 8299.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '8299.TW' LIMIT 1) WHERE stock_id = '7fbb0acd-4121-4cb1-abbc-7a393d0c33d0' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '8299.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '7fbb0acd-4121-4cb1-abbc-7a393d0c33d0';
DELETE FROM stocks WHERE id = '7fbb0acd-4121-4cb1-abbc-7a393d0c33d0';
-- PAYPAL (US, name="PayPal Holdings, Inc.", 1 linkages) → PYPL
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PYPL' LIMIT 1) WHERE stock_id = 'a485f0a7-f846-401b-aa13-1d1caebe30eb' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PYPL' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'a485f0a7-f846-401b-aa13-1d1caebe30eb';
DELETE FROM stocks WHERE id = 'a485f0a7-f846-401b-aa13-1d1caebe30eb';
-- 2357 (TW, name="華碩", 1 linkages) → 2357.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '2357.TW' LIMIT 1) WHERE stock_id = '1ee2a195-5483-4484-b6c7-3207af572238' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '2357.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '1ee2a195-5483-4484-b6c7-3207af572238';
DELETE FROM stocks WHERE id = '1ee2a195-5483-4484-b6c7-3207af572238';
-- PURE.US (US, name="Pure Storage, Inc.", 1 linkages) → PSTG
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PSTG' LIMIT 1) WHERE stock_id = '1769a5ab-df9e-4d6e-94dd-6e315744477e' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PSTG' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '1769a5ab-df9e-4d6e-94dd-6e315744477e';
DELETE FROM stocks WHERE id = '1769a5ab-df9e-4d6e-94dd-6e315744477e';
-- UMC (TW, name="聯華電子", 0 linkages) → 2303.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '2303.TW' LIMIT 1) WHERE stock_id = 'b6316e9b-938a-4f39-a606-2dc37204a04d' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '2303.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'b6316e9b-938a-4f39-a606-2dc37204a04d';
DELETE FROM stocks WHERE id = 'b6316e9b-938a-4f39-a606-2dc37204a04d';
-- PSMC (TW, name="力積電", 0 linkages) → 6770.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '6770.TW' LIMIT 1) WHERE stock_id = '35bdaf89-f26b-43a7-9049-570360c2f521' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '6770.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '35bdaf89-f26b-43a7-9049-570360c2f521';
DELETE FROM stocks WHERE id = '35bdaf89-f26b-43a7-9049-570360c2f521';
-- FLCL (US, name="Cloudflare", 0 linkages) → NET
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1) WHERE stock_id = 'afbf7e21-aff0-4415-9cfc-345bf7b06f75' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'afbf7e21-aff0-4415-9cfc-345bf7b06f75';
DELETE FROM stocks WHERE id = 'afbf7e21-aff0-4415-9cfc-345bf7b06f75';
-- BRCM (US, name="Broadcom Inc.", 2 linkages) → AVGO
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'AVGO' LIMIT 1) WHERE stock_id = 'ac3a7970-e946-4dbd-baec-a76615409b3c' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'AVGO' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'ac3a7970-e946-4dbd-baec-a76615409b3c';
DELETE FROM stocks WHERE id = 'ac3a7970-e946-4dbd-baec-a76615409b3c';
-- CNFL (US, name="Confluent, Inc.", 1 linkages) → CFLT
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'CFLT' LIMIT 1) WHERE stock_id = '4493a65a-6c3c-4782-92bf-9d56bd661315' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'CFLT' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '4493a65a-6c3c-4782-92bf-9d56bd661315';
DELETE FROM stocks WHERE id = '4493a65a-6c3c-4782-92bf-9d56bd661315';
-- 00631L (TW, name="元大台灣50正2", 1 linkages) → 00631L.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '00631L.TW' LIMIT 1) WHERE stock_id = 'd954c49e-e0ce-4a45-a58f-875b89a07fbf' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '00631L.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'd954c49e-e0ce-4a45-a58f-875b89a07fbf';
DELETE FROM stocks WHERE id = 'd954c49e-e0ce-4a45-a58f-875b89a07fbf';
-- ASUS (TW, name="華碩", 1 linkages) → 2357.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '2357.TW' LIMIT 1) WHERE stock_id = '4541e9de-189a-468e-9f56-0ce836349f22' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '2357.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '4541e9de-189a-468e-9f56-0ce836349f22';
DELETE FROM stocks WHERE id = '4541e9de-189a-468e-9f56-0ce836349f22';
-- AIRBUS (US, name="Airbus", 1 linkages) → EADSY
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'EADSY' LIMIT 1) WHERE stock_id = 'b720b673-0911-43a1-ac42-85724a4e5694' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'EADSY' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'b720b673-0911-43a1-ac42-85724a4e5694';
DELETE FROM stocks WHERE id = 'b720b673-0911-43a1-ac42-85724a4e5694';
-- SERVICENOW (US, name="ServiceNow", 1 linkages) → NOW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'NOW' LIMIT 1) WHERE stock_id = '3d537163-2960-4da4-84ce-508f8efa6197' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'NOW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '3d537163-2960-4da4-84ce-508f8efa6197';
DELETE FROM stocks WHERE id = '3d537163-2960-4da4-84ce-508f8efa6197';
-- ORACLE (US, name="Oracle", 1 linkages) → ORCL
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'ORCL' LIMIT 1) WHERE stock_id = 'a3258e41-38b5-4e3f-8f11-5e3f30719518' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'ORCL' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'a3258e41-38b5-4e3f-8f11-5e3f30719518';
DELETE FROM stocks WHERE id = 'a3258e41-38b5-4e3f-8f11-5e3f30719518';
-- SALESFORCE (US, name="Salesforce", 1 linkages) → CRM
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'CRM' LIMIT 1) WHERE stock_id = 'd7b71b09-855e-4122-82f1-f5618a8bbf97' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'CRM' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'd7b71b09-855e-4122-82f1-f5618a8bbf97';
DELETE FROM stocks WHERE id = 'd7b71b09-855e-4122-82f1-f5618a8bbf97';
-- FLARE (US, name="Cloudflare", 1 linkages) → NET
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1) WHERE stock_id = '91ce8112-94de-4235-899d-7445f89b0f05' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'NET' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '91ce8112-94de-4235-899d-7445f89b0f05';
DELETE FROM stocks WHERE id = '91ce8112-94de-4235-899d-7445f89b0f05';
-- SEAGATE (US, name="Seagate Technology Holdings plc", 1 linkages) → STX
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'STX' LIMIT 1) WHERE stock_id = '32f8e3e1-7aeb-4911-bd71-9670830a54e7' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'STX' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '32f8e3e1-7aeb-4911-bd71-9670830a54e7';
DELETE FROM stocks WHERE id = '32f8e3e1-7aeb-4911-bd71-9670830a54e7';
-- STELLANTIS (US, name="Stellantis", 1 linkages) → STLA
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'STLA' LIMIT 1) WHERE stock_id = 'dd67ea16-c9f3-4643-92df-a53ed9a0038b' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'STLA' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = 'dd67ea16-c9f3-4643-92df-a53ed9a0038b';
DELETE FROM stocks WHERE id = 'dd67ea16-c9f3-4643-92df-a53ed9a0038b';
-- AMAZON (US, name="Amazon", 1 linkages) → AMZN
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'AMZN' LIMIT 1) WHERE stock_id = '2a082cb2-5005-4bda-8797-58e48692ee03' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'AMZN' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '2a082cb2-5005-4bda-8797-58e48692ee03';
DELETE FROM stocks WHERE id = '2a082cb2-5005-4bda-8797-58e48692ee03';
-- 3596 (TW, name="智易", 1 linkages) → 3596.TW
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = '3596.TW' LIMIT 1) WHERE stock_id = '901efb87-da4e-4b23-bbdb-970d11448e6d' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = '3596.TW' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '901efb87-da4e-4b23-bbdb-970d11448e6d';
DELETE FROM stocks WHERE id = '901efb87-da4e-4b23-bbdb-970d11448e6d';
-- IMPINJ (US, name="Impinj", 1 linkages) → PI
UPDATE post_stocks SET stock_id = (SELECT id FROM stocks WHERE ticker = 'PI' LIMIT 1) WHERE stock_id = '1efcee47-417c-4906-a863-3a597cfb51b6' AND NOT EXISTS (SELECT 1 FROM post_stocks ps2 WHERE ps2.post_id = post_stocks.post_id AND ps2.stock_id = (SELECT id FROM stocks WHERE ticker = 'PI' LIMIT 1));
DELETE FROM post_stocks WHERE stock_id = '1efcee47-417c-4906-a863-3a597cfb51b6';
DELETE FROM stocks WHERE id = '1efcee47-417c-4906-a863-3a597cfb51b6';
COMMIT;

-- ============================================================
-- BUCKET B — DELETE (47 rows)
-- Cascade-delete post_stocks then the stock row.
-- ============================================================
BEGIN;
-- PANTRY (US, name="Pantry Inc.", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'e7ecd81f-3355-47ac-b141-2d9a9fa52fd4';
DELETE FROM stocks WHERE id = 'e7ecd81f-3355-47ac-b141-2d9a9fa52fd4';
-- 566.TW (TW, name="日月光投控", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'c4910e60-6a84-44dc-a5b3-f0201b81a7dd';
DELETE FROM stocks WHERE id = 'c4910e60-6a84-44dc-a5b3-f0201b81a7dd';
-- 569 (TW, name="聖暉工程科技股份有限公司", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '3c018acd-1dfe-4dba-af4d-51239a054842';
DELETE FROM stocks WHERE id = '3c018acd-1dfe-4dba-af4d-51239a054842';
-- 566 (TW, name="精測股份有限公司", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '0e02385c-0718-456d-bfff-af6944574a90';
DELETE FROM stocks WHERE id = '0e02385c-0718-456d-bfff-af6944574a90';
-- VIS (TW, name="威盛", 1 linkages) [wrong-market (master has VIS in US)]
DELETE FROM post_stocks WHERE stock_id = 'fb9b779e-9e2b-4df4-9eb5-b939a8980e36';
DELETE FROM stocks WHERE id = 'fb9b779e-9e2b-4df4-9eb5-b939a8980e36';
-- STARLBS (US, name="Starbox Holdings Ltd.", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '3847dd61-5ff4-4f3e-b24c-01adae4e2633';
DELETE FROM stocks WHERE id = '3847dd61-5ff4-4f3e-b24c-01adae4e2633';
-- 366 (TW, name="366", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '6e6187a8-55d4-4137-bbd6-fd11c27a1c4d';
DELETE FROM stocks WHERE id = '6e6187a8-55d4-4137-bbd6-fd11c27a1c4d';
-- SPACEX (US, name="SpaceX", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '38bc3abf-2a87-4de4-8ca6-3e8013040686';
DELETE FROM stocks WHERE id = '38bc3abf-2a87-4de4-8ca6-3e8013040686';
-- CMO (US, name="CMO", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '6b3018db-dcba-426a-85d5-8bac91b7b218';
DELETE FROM stocks WHERE id = '6b3018db-dcba-426a-85d5-8bac91b7b218';
-- CRDL.TW (TW, name="創王", 1 linkages) [not-in-master]
DELETE FROM post_stocks WHERE stock_id = '0908204c-64f6-4504-b374-c727cf56b734';
DELETE FROM stocks WHERE id = '0908204c-64f6-4504-b374-c727cf56b734';
-- 5349.TW (TW, name="馮君", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'a346e7d7-ec16-4526-abd8-156798804576';
DELETE FROM stocks WHERE id = 'a346e7d7-ec16-4526-abd8-156798804576';
-- 2888.TW (TW, name="First Financial Holding Co., Ltd.", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'e059912b-09b0-41e8-8093-a55e03f26a90';
DELETE FROM stocks WHERE id = 'e059912b-09b0-41e8-8093-a55e03f26a90';
-- DIOT (US, name="DIOT", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'a1d5cd64-2426-49e1-aff1-8f25b6697408';
DELETE FROM stocks WHERE id = 'a1d5cd64-2426-49e1-aff1-8f25b6697408';
-- ^TWII (TW, name="TWSE Weighted Index", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '40c28a47-deba-4d8c-89a7-23d0fdf17b20';
DELETE FROM stocks WHERE id = '40c28a47-deba-4d8c-89a7-23d0fdf17b20';
-- DI0T (TW, name="DI0T", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '37b50d7f-969b-411f-9224-ef315872c350';
DELETE FROM stocks WHERE id = '37b50d7f-969b-411f-9224-ef315872c350';
-- CHROME (US, name="Chrome", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'be1b0883-0c46-4654-b21f-279cd586a247';
DELETE FROM stocks WHERE id = 'be1b0883-0c46-4654-b21f-279cd586a247';
-- ANDROID (US, name="Android", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '1e69223d-7415-449b-a4c7-c25955d152ce';
DELETE FROM stocks WHERE id = '1e69223d-7415-449b-a4c7-c25955d152ce';
-- CLAUDE (US, name="Claude", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'a0b75d4c-7eb7-46df-a7ef-6b57b25af0ca';
DELETE FROM stocks WHERE id = 'a0b75d4c-7eb7-46df-a7ef-6b57b25af0ca';
-- YOUTUBE (US, name="YouTube", 0 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '4cb1cb74-7c5d-4818-a053-64832a6b170a';
DELETE FROM stocks WHERE id = '4cb1cb74-7c5d-4818-a053-64832a6b170a';
-- VMWARE (US, name="VMware, Inc.", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'd5472247-b710-40d7-95c4-20c61ba5ded2';
DELETE FROM stocks WHERE id = 'd5472247-b710-40d7-95c4-20c61ba5ded2';
-- ERG (HK, name="ERG", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '9948872e-1775-4499-9e53-513e20b0684a';
DELETE FROM stocks WHERE id = '9948872e-1775-4499-9e53-513e20b0684a';
-- US (US, name="US", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '7ccf0abc-0b29-46fc-8ac4-70ae29afdf6e';
DELETE FROM stocks WHERE id = '7ccf0abc-0b29-46fc-8ac4-70ae29afdf6e';
-- GPT-4 (CRYPTO, name="GPT-4", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'a9d063e7-7e5d-4d7f-95a3-e1c45f2b230e';
DELETE FROM stocks WHERE id = 'a9d063e7-7e5d-4d7f-95a3-e1c45f2b230e';
-- LLAMA 3 (CRYPTO, name="Llama 3", 1 linkages) [not-in-master]
DELETE FROM post_stocks WHERE stock_id = '44bcc67a-5be7-4fb0-8034-4eca99cbe183';
DELETE FROM stocks WHERE id = '44bcc67a-5be7-4fb0-8034-4eca99cbe183';
-- CLAUDE 3.5 (CRYPTO, name="Claude 3.5", 1 linkages) [not-in-master]
DELETE FROM post_stocks WHERE stock_id = '2a20e333-b84d-43c1-b41a-712c566692b4';
DELETE FROM stocks WHERE id = '2a20e333-b84d-43c1-b41a-712c566692b4';
-- MODEL Y (US, name="Model Y", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '980fc9d3-35e1-4d62-bf54-a23df1340878';
DELETE FROM stocks WHERE id = '980fc9d3-35e1-4d62-bf54-a23df1340878';
-- MODEL 3 (US, name="Model 3", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '07c3bd65-07c9-4429-bff7-25b45e2f2ace';
DELETE FROM stocks WHERE id = '07c3bd65-07c9-4429-bff7-25b45e2f2ace';
-- MODEL X (US, name="Model X", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'ac163aae-4260-4082-89dd-138b40032f7a';
DELETE FROM stocks WHERE id = 'ac163aae-4260-4082-89dd-138b40032f7a';
-- ASTERRA LABS (US, name="ASTERRA LABS", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '7642e735-301e-4799-891f-9ff296abcaaf';
DELETE FROM stocks WHERE id = '7642e735-301e-4799-891f-9ff296abcaaf';
-- DYNA (TW, name="順達", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '041bedbd-80bd-4beb-95c5-5e9fa7670d94';
DELETE FROM stocks WHERE id = '041bedbd-80bd-4beb-95c5-5e9fa7670d94';
-- 366 E (TW, name="366E", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'ec788635-0d0d-4430-802a-89173d80a4de';
DELETE FROM stocks WHERE id = 'ec788635-0d0d-4430-802a-89173d80a4de';
-- CRYSTAL (US, name="Crystal", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'f3360bb9-dcc5-43c4-91f7-af1a63ae7a4a';
DELETE FROM stocks WHERE id = 'f3360bb9-dcc5-43c4-91f7-af1a63ae7a4a';
-- 2542 (TW, name="元大台灣50", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '8fe23e9b-ac20-4226-922b-14ae58d7dd89';
DELETE FROM stocks WHERE id = '8fe23e9b-ac20-4226-922b-14ae58d7dd89';
-- CNMRBL (US, name="CNM Resources Limited", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'c5d7dc69-0d15-491d-a96f-1b7c1fd1cc02';
DELETE FROM stocks WHERE id = 'c5d7dc69-0d15-491d-a96f-1b7c1fd1cc02';
-- PLANTLY (US, name="Plantly", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = '59222de9-c882-4ec6-b9a0-7e96f8f8e8e0';
DELETE FROM stocks WHERE id = '59222de9-c882-4ec6-b9a0-7e96f8f8e8e0';
-- UNIQLO (US, name="Uniqlo", 1 linkages) [ticker-blacklisted]
DELETE FROM post_stocks WHERE stock_id = 'd059cb80-6401-45b1-832f-e19d57c0a617';
DELETE FROM stocks WHERE id = 'd059cb80-6401-45b1-832f-e19d57c0a617';
-- 9970.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'a4f34b73-0f91-4679-b3fb-bbfa6da3bd4d';
DELETE FROM stocks WHERE id = 'a4f34b73-0f91-4679-b3fb-bbfa6da3bd4d';
-- 9972.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'd566158c-7680-416f-86d2-92eee11828b5';
DELETE FROM stocks WHERE id = 'd566158c-7680-416f-86d2-92eee11828b5';
-- 9977.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = '043d43f5-2587-4d8f-958e-8f075faa90f5';
DELETE FROM stocks WHERE id = '043d43f5-2587-4d8f-958e-8f075faa90f5';
-- 9995.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'db5e570c-669e-4ded-91c0-10b3fc89ad3e';
DELETE FROM stocks WHERE id = 'db5e570c-669e-4ded-91c0-10b3fc89ad3e';
-- 9971.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = '9169f37a-6b2e-4f85-9895-06106123afbc';
DELETE FROM stocks WHERE id = '9169f37a-6b2e-4f85-9895-06106123afbc';
-- 9975.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'a80c7776-d9a4-4375-a0b9-e2a3c009f38c';
DELETE FROM stocks WHERE id = 'a80c7776-d9a4-4375-a0b9-e2a3c009f38c';
-- 9978.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'bab6e6ef-48d8-4266-b9b8-cad7d6d16079';
DELETE FROM stocks WHERE id = 'bab6e6ef-48d8-4266-b9b8-cad7d6d16079';
-- 9973.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = '1dcaf4da-cfb1-4e66-acd1-3e9f3c2aaa6e';
DELETE FROM stocks WHERE id = '1dcaf4da-cfb1-4e66-acd1-3e9f3c2aaa6e';
-- 9974.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = '34a0d74a-22a2-48af-a96b-36d773d196b3';
DELETE FROM stocks WHERE id = '34a0d74a-22a2-48af-a96b-36d773d196b3';
-- 9976.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = 'f8130e99-fbf5-40bb-8fd6-16088c0ad6d7';
DELETE FROM stocks WHERE id = 'f8130e99-fbf5-40bb-8fd6-16088c0ad6d7';
-- 9979.TW (TW, name="寶", 1 linkages) [name-blacklisted (no master rescue)]
DELETE FROM post_stocks WHERE stock_id = '8d09390f-b743-4843-882a-f47ed09c7436';
DELETE FROM stocks WHERE id = '8d09390f-b743-4843-882a-f47ed09c7436';
COMMIT;

-- ============================================================
-- BUCKET C — RENAME (25 rows)
-- Heal name to the canonical master value. Linkages preserved.
-- ============================================================
BEGIN;
-- CRCL (US, 1 linkages): "CRCL" → "Circle Internet Group, Inc. Class A Common Stock" [master-name-disagrees]
UPDATE stocks SET name = 'Circle Internet Group, Inc. Class A Common Stock' WHERE id = 'b8017f82-86c0-4d21-b5f5-2b7f8adc4a64';
-- ASML (US, 2 linkages): "ASML" → "ASML Holding N.V. - New York Registry Shares" [master-name-disagrees]
UPDATE stocks SET name = 'ASML Holding N.V. - New York Registry Shares' WHERE id = '60fb407d-b8e5-4744-9f79-f43b61298582';
-- AAOI (US, 1 linkages): "AAOI" → "Applied Optoelectronics, Inc." [master-name-disagrees]
UPDATE stocks SET name = 'Applied Optoelectronics, Inc.' WHERE id = '3e2f1425-0399-4866-92c6-a186d39319fc';
-- IBM (US, 2 linkages): "IBM" → "International Business Machines Corporation Common Stock" [master-name-disagrees]
UPDATE stocks SET name = 'International Business Machines Corporation Common Stock' WHERE id = 'a60cd947-79e2-42d2-9d92-24896ed73b9e';
-- 8086.TW (TW, 2 linkages): "宏捷" → "宏捷科" [master-name-disagrees]
UPDATE stocks SET name = '宏捷科' WHERE id = '84255b23-0c43-4d85-956c-377ebb714dc1';
-- 2353.TW (TW, 8 linkages): "宏捷" → "宏碁" [master-name-disagrees]
UPDATE stocks SET name = '宏碁' WHERE id = '605778fc-b4b6-4d39-ba1a-14ca8dadd161';
-- 3044.TW (TW, 1 linkages): "馮君" → "健鼎" [rescued-from-name-blacklist]
UPDATE stocks SET name = '健鼎' WHERE id = '28a8a53e-e1b2-4bef-9021-50e8cd68d4c9';
-- 3622.TW (TW, 1 linkages): "馮君" → "洋華" [rescued-from-name-blacklist]
UPDATE stocks SET name = '洋華' WHERE id = '8e4e51fb-67f8-4439-9bc2-8fa114aec7d0';
-- 4966.TW (TW, 1 linkages): "馮君" → "譜瑞-KY" [rescued-from-name-blacklist]
UPDATE stocks SET name = '譜瑞-KY' WHERE id = '95f4d9f9-b181-4419-8c6d-5bc327e1db80';
-- 6121.TW (TW, 3 linkages): "馮君" → "新普" [rescued-from-name-blacklist]
UPDATE stocks SET name = '新普' WHERE id = '4d9c705b-43b1-4768-94db-b84e566ff17a';
-- 6244.TW (TW, 1 linkages): "馮君" → "茂迪" [rescued-from-name-blacklist]
UPDATE stocks SET name = '茂迪' WHERE id = '52b229e4-9f2e-41cb-8add-bd7024083a8e';
-- 6435.TW (TW, 3 linkages): "馮君" → "大中" [rescued-from-name-blacklist]
UPDATE stocks SET name = '大中' WHERE id = '08e4f25c-f288-49f9-b9ba-8c08b2b0b05f';
-- 6441.TW (TW, 1 linkages): "馮君" → "廣錠" [rescued-from-name-blacklist]
UPDATE stocks SET name = '廣錠' WHERE id = 'c17b89fa-a7a0-471c-b93a-4b68304bf5f4';
-- 6533.TW (TW, 4 linkages): "馮君" → "晶心科" [rescued-from-name-blacklist]
UPDATE stocks SET name = '晶心科' WHERE id = '9987a6c1-ecb4-46a3-b3b5-956af314134e';
-- 2883.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "凱基金" [master-name-disagrees]
UPDATE stocks SET name = '凱基金' WHERE id = 'ab1e1db0-16a7-4afe-9ce4-7bdc7c724cbf';
-- 2886.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "兆豐金" [master-name-disagrees]
UPDATE stocks SET name = '兆豐金' WHERE id = 'c454211b-7172-431c-b4ff-b89fcf0728a7';
-- 2892.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "第一金" [master-name-disagrees]
UPDATE stocks SET name = '第一金' WHERE id = 'c749f1d6-9a65-4e04-b388-300d31c5efe7';
-- 2882.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "國泰金" [master-name-disagrees]
UPDATE stocks SET name = '國泰金' WHERE id = '58841c0f-52a7-494b-b555-c305f46dfaab';
-- 2881.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "富邦金" [master-name-disagrees]
UPDATE stocks SET name = '富邦金' WHERE id = '8d828183-18b7-479e-a27e-ddeab25db7b2';
-- 2885.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "元大金" [master-name-disagrees]
UPDATE stocks SET name = '元大金' WHERE id = '89945445-747a-418b-a8c3-67b5f71420e0';
-- 2890.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "永豐金" [master-name-disagrees]
UPDATE stocks SET name = '永豐金' WHERE id = '40c892a8-8da4-48f2-bc73-9037a4c90534';
-- 2887.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "台新新光金" [master-name-disagrees]
UPDATE stocks SET name = '台新新光金' WHERE id = '72651baa-c620-46a2-bc6d-76c5f72c9c55';
-- 2889.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "國票金" [master-name-disagrees]
UPDATE stocks SET name = '國票金' WHERE id = '42068099-4f1b-42fe-ae44-e79463932e9f';
-- 2897.TW (TW, 0 linkages): "First Financial Holding Co., Ltd." → "王道銀行" [master-name-disagrees]
UPDATE stocks SET name = '王道銀行' WHERE id = 'd10afc03-f799-4ff5-8120-5c1f23cecc2f';
-- NVTS (US, 1 linkages): "NVTS" → "Navitas Semiconductor Corporation" [master-name-disagrees]
UPDATE stocks SET name = 'Navitas Semiconductor Corporation' WHERE id = 'fd71fb60-7e28-4361-9f02-f92551a8d900';
COMMIT;

